#!/usr/bin/env bash
#this script pings an IP address passed as an argument


echo "Enter your IP address"
read address
if [ "$address" = "$address" ];
then
        ping -c 5 $address

else

        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"

fi
