#!/usr/bin/env bash
#this file checks if file: school exist
File=school
if [ -f "$File" ]; then
        echo "$File file exists"
else
        echo "$File file does not exist"
fi

if [ -s "$File" ]; then
        echo "$File file is not empty"
else
        echo "$File file is empty"
fi

if [ -f "$File" ]; then
        echo "$File is a regular file"
else
        echo "nothing"
fi
